### PR TITLE
add go.mod, update gopsutil

### PR DESCRIPTION
**Pull request by Kubuxu**
Solves gopsutil build issues on Darwin.

Signed-off-by: Jakub Sztandera <kubuxu@protocol.ai>

### CODE REVIEW

**Comment by schmoove** [comment]
Can this PR please be merged? Unable to use this lib otherwise

**Comment by yotamloe** [comment]
@schmoove and @kubuxu Thank you for your contribution, your changes are included in #6

**Comment by newyork75** [comment]
Hello. Sorry for my comment in this PR. I get two error messages in version v1.0.1.

`logziosender.go:119:11: cannot use q (type *inMemoryQueue.ConcurrentQueue) as type genericQueue in assignment:
        *inMemoryQueue.ConcurrentQueue does not implement genericQueue (wrong type for Close method)
                have Close()
                want Close() error`

Missing return value `error` in logzio-go/inMemoryQueue/inMemoryQueue.go:84

`logziosender.go:127:11: cannot use q (type *goque.Queue) as type genericQueue in assignment:
        *goque.Queue does not implement genericQueue (wrong type for Close method)
                have Close() error
                want Close()`

Missing return value `error` in logzio-go/genericQueue.go:10

**Comment by yotamloe** [comment]
@newyork75 Hey thank you for reporting this issue, I was able to recreate the issue, it happened because this project used an old version of `github.com/beeker1121/goque` I opened a new PR (#7) for the requested changes. Meanwhile, you can use the `v1.1.1-alpha` release with the updated version until we merge the changes. Please let us know if that's resolved your issue

**Comment by newyork75** [comment]
@yotamloe Thanks for your quick response. v1.1.1-alpha works fine for me.

**Comment by yotamloe** [comment]
@newyork75 Amazing. just so you know we also released a new official v1.0.2 with few updates that you can use.

**Pull request closed without merging**
